### ISSUE TITLE
[ALDB Feature req.]: Add Level Tracking (and related features) to the Track Tracker

### ISSUE THREAD

**Issue by MrLar** [MrLar/AzurLaneToolIssues#1]
### Before submitting, I have

- [X] Double-checked existing Issues for a similar feature (including closed ones).
- [X] Double-checked the feature does not exist already with either same or slightly different functionality.
- [X] Double-checked the feature has not been rejected before.
- [X] Ensured the feature makes sense given the context of the game

### Describe what you would like us to add

The tech tracker could use the addition of tracking levels. The following is of consideration:
- [x] Tracking levels 1 to 125
- [x] Adjusting cog. chips needed accordingly
- [x] Sort by Level
- [x] Bulins needed (SR only)

### Additional context

Any one is free to suggest more stuff in this issue thread.

**Comment by MrLar** [comment]
This will land in version 1.4.8.
